# temproary (manually created) file to store the default interpolation configuration
# ToDO: create a function to generate this file from modInp.yml
act2ainp: back.inter.forth
act2aout: back.inter.forth
af.lo: back.inter.forth
af.up: back.inter.forth
afc.lo: back.inter.forth
afc.up: back.inter.forth
afs.lo: back.inter.forth
afs.up: back.inter.forth
agg: back.inter.forth
ava.lo: back.inter.forth
ava.up: back.inter.forth
avarom: back.inter.forth
cact2cout: back.inter.forth
cap2act: back.inter.forth
cap2ainp: back.inter.forth
cap2aout: back.inter.forth
cap2cat: back.inter.forth
cap2stg: back.inter.forth
card: back.inter.forth
cdst2ainp: back.inter.forth
cdst2aout: back.inter.forth
charge: ''
cinp.lo: back.inter.forth
cinp.up: back.inter.forth
cinp2ainp: back.inter.forth
cinp2aout: back.inter.forth
cinp2ginp: back.inter.forth
cinp2use: back.inter.forth
combustion: back.inter.forth
cost: back.inter.forth
cout.lo: back.inter.forth
cout.up: back.inter.forth
cout2ainp: back.inter.forth
cout2aout: back.inter.forth
csrc2ainp: back.inter.forth
csrc2aout: back.inter.forth
cvarom: back.inter.forth
dem: back.inter.forth
discount: back.inter.forth
dummyExport: back.inter.forth
dummyImport: back.inter.forth
emis: back.inter.forth
exp.lo: back.inter.forth
exp.up: back.inter.forth
fixom: back.inter.forth
fraction: back.inter.forth
ginp2use: back.inter.forth
imp.lo: back.inter.forth
imp.up: back.inter.forth
inpcost: back.inter.forth
inpeff: back.inter.forth
invcost: back.inter.forth
retcost: back.inter.forth
markup: back.inter.forth
ncap2ainp: back.inter.forth
ncap2aout: back.inter.forth
ncap2stg: ''
olife: back.inter.forth
ord: back.inter.forth
outcost: back.inter.forth
outeff: back.inter.forth
price: back.inter.forth
rampdown: back.inter.forth
rampup: back.inter.forth
res.lo: back.inter.forth
res.up: back.inter.forth
reserve: back.inter.forth
rhs: back.inter.forth
share.lo: back.inter.forth
share.up: back.inter.forth
stg2ainp: back.inter.forth
stg2aout: back.inter.forth
stgcost: back.inter.forth
stgeff: back.inter.forth
stock: back.inter.forth
cap.lo: inter.forth
cap.up: inter.forth
ncap.lo: inter.forth
ncap.up: inter.forth
ret.lo: inter.forth
ret.up: inter.forth
subs: inter.forth
tax: inter.forth
teff: back.inter.forth
use2cact: back.inter.forth
value: back.inter.forth
varom: back.inter.forth
waf.lo: back.inter.forth
waf.up: back.inter.forth
wafc.lo: back.inter.forth
wafc.up: back.inter.forth
wafs.lo: back.inter.forth
wafs.up: back.inter.forth
wava.lo: back.inter.forth
wava.up: back.inter.forth
wcinp.lo: back.inter.forth
wcinp.up: back.inter.forth
wcout.lo: back.inter.forth
wcout.up: back.inter.forth
wval: back.inter.forth
