act2ainp: 0.0
act2aout: 0.0
af.lo: 0.0
af.up: 1.0
afc.lo: 0.0
afc.up: .inf
afs.lo: 0.0
afs.up: .inf
agg: 0.0
ava.lo: 0.0
ava.up: .inf
avarom: 0.0
cact2cout: 1.0
cap2act: 1.0
cap2ainp: 0.0
cap2aout: 0.0
cap2cat: 1.0
cap2stg: 1.0
card: 1.0
cdst2ainp: 0.0
cdst2aout: 0.0
charge: 0.0
cinp.lo: 0.0
cinp.up: .inf
cinp2ainp: 0.0
cinp2aout: 0.0
cinp2ginp: 1.0
cinp2use: 1.0
combustion: 1.0
cost: 0.0
cout.lo: 0.0
cout.up: .inf
cout2ainp: 0.0
cout2aout: 0.0
csrc2ainp: 0.0
csrc2aout: 0.0
cvarom: 0.0
dem: 0.0
discount: 0.0
dummyExport: .inf
dummyImport: .inf
emis: 0.0
exp.lo: 0.0
exp.up: .inf
fixom: 0.0
ginp2use: 1.0
imp.lo: 0.0
imp.up: .inf
inpcost: 0.0
inpeff: 1.0
invcost: 0.0
markup: 0.0
ncap2ainp: 0.0
ncap2aout: 0.0
ncap2stg: 0.0
olife: 1.0
ord: 1.0
outcost: 0.0
outeff: 1.0
price: 0.0
rampdown: .inf
rampup: .inf
res.lo: 0.0
res.up: .inf
reserve: .inf
rhs: 0.0
share.lo: 0.0
share.up: 1.0
stg2ainp: 0.0
stg2aout: 0.0
stgcost: 0.0
stgeff: 1.0
stock: 0.0
subs: 0.0
tax: 0.0
teff: 1.0
use2cact: 1.0
value: 0.0
varom: 0.0
waf.lo: 0.0
waf.up: 0.0
wafc.lo: 0.0
wafc.up: 0.0
wafs.lo: 0.0
wafs.up: 0.0
wava.lo: 0.0
wava.up: 0.0
wcinp.lo: 0.0
wcinp.up: 0.0
wcout.lo: 0.0
wcout.up: 0.0
wval: 0.0
cap.lo: 0.0
cap.up: .inf
ncap.lo: 0.0
ncap.up: .inf
ret.lo: 0.0
ret.up: .inf
retcost: 0.0
