#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom data.table :=
#' @importFrom data.table .BY
#' @importFrom data.table .EACHI
#' @importFrom data.table .GRP
#' @importFrom data.table .I
#' @importFrom data.table .N
#' @importFrom data.table .NGRP
#' @importFrom data.table .SD
#' @importFrom data.table as.data.table
#' @importFrom data.table data.table
#' @importFrom data.table is.data.table
#' @importFrom data.table rbindlist
#' @importFrom data.table setcolorder
#' @importFrom dplyr across
#' @importFrom dplyr add_row
#' @importFrom dplyr all_of
#' @importFrom dplyr any_of
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_rows
#' @importFrom dplyr collect
#' @importFrom dplyr filter
#' @importFrom dplyr full_join
#' @importFrom dplyr if_else
#' @importFrom dplyr inner_join
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr right_join
#' @importFrom dplyr select
#' @importFrom dplyr slice_head
#' @importFrom dplyr summarize
#' @importFrom generics interpolate
#' @importFrom options opt
#' @importFrom options opt_set
#' @importFrom purrr list_flatten
#' @importFrom rlang is_empty
#' @importFrom rlang is_null
#' @importFrom tibble as_tibble
#' @importFrom tibble is_tibble
#' @importFrom tibble tibble
#' @importFrom tidyr complete
#' @importFrom tidyr crossing
#' @importFrom tidyr drop_na
#' @importFrom tidyr expand
#' @importFrom tidyr expand_grid
#' @importFrom tidyr fill
#' @importFrom tidyr full_seq
#' @importFrom tidyr nesting
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr pivot_wider
#' @importFrom tidyr replace_na
#' @importFrom tidyr unite
## usethis namespace: end
NULL
